config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'products/show'
  resources :subcategories
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories, only: [:show]
  devise_for :users, controllers: { registrations: 'users/registrations'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get '/showrooms', to: 'showrooms#index'
  # get '/showrooms/new', to: 'showrooms#new'
  # post '/showrooms/create', to: 'showrooms#create'
  resources :showrooms, only: [:index, :new, :create]
  resources :products, only: [:show]
  root to: 'pages#home'

  namespace :dashboard do
    root to: 'pages#home'
  end
end

app/models/subcategory.rb
# frozen_string_literal: true

class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :products, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true, length: { maximum: 250 }
end

app/controllers/subcategories_controller.rb
# frozen_string_literal: true

class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: %i[show]

  # GET /subcategorys/1
  def show
    @products = @subcategory.products
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subcategory
    @subcategory = Subcategory.find(params[:id])
  end
end

app/helpers/subcategories_helper.rb
# frozen_string_literal: true

module SubcategoriesHelper
end

app/views/subcategories/show.html.erb
<section class="bg-white dark:bg-gray-900">

  <%if @subcategory && @subcategory.image.attached? %>
    <div class="bg-cover bg-center bg-repeat flex justify-center items-center relative", style="background-image: url('<%= url_for(@subcategory.image) %>'); height: 150px; width: 100%;">
      <div class="absolute top-0 left-0 right-0 bottom-0 bg-black opacity-40 z-40 h-full" style="background-color: black; opacity: 0.4; height: 100%;"> </div>
      <div class="w-full relative z-50">
        <div class="container text-center mx-auto">
          <div class="text-white text-6xl"><%= @subcategory.name.upcase %></div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="container px-6 py-10 mx-auto">

      <div class="grid grid-cols-1 gap-8 mt-4 xl:mt-8 xl:gap-4 md:grid-cols-2 xl:grid-cols-3">
        <% @products&.each do |product| %>
          <div class="bg-gray-100 overflow-hidden bg-white rounded-lg shadow-lg dark:bg-gray-800 hover:border-4 ">
              <div class="px-4 py-2">
                  <h2 class="text-3xl font-bold text-gray-800 uppercase dark:text-white"><%= link_to product.product_name, product_path(product.id) %></h2>
                  <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">Lorem ipsum dolor</p>
              </div>

              <img class="w-full h-48 mt-2" src=<%= url_for(product.image) if  product.image.attached? %> alt="NIKE AIR">

              <div class="flex items-center justify-between px-4 py-2 bg-gray-900">
                  <h1 class="text-lg font-bold text-white">$<%= product.price %></h1>
                  <div class="border border-black" >
                    <%= form_with model: product.line_items.new, url: line_items_path, class: '' do |form| %>
                        <%= form.hidden_field :product_id, value: product.id %>
                        <%= form.number_field :quantity, min: 1, class: "w-12 px-2 py-1 text-xs font-semibold text-gray-900 uppercase transition-colors duration-200 transform bg-white rounded hover:bg-gray-200 focus:bg-gray-400 focus:outline-none" %>
                        <%= form.submit 'Add to cart', class: 'px-2 py-1 text-xs font-semibold text-gray-900 uppercase transition-colors duration-200 transform bg-white rounded hover:bg-gray-200 focus:bg-gray-400 focus:outline-none'%>
                    <% end %>
                  </div>
              </div>
          </div>
        <% end %>
      </div>
  </div>

</section>