config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'products/show'
  resources :subcategories
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories, only: [:show]
  devise_for :users, controllers: { registrations: 'users/registrations'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get '/showrooms', to: 'showrooms#index'
  # get '/showrooms/new', to: 'showrooms#new'
  # post '/showrooms/create', to: 'showrooms#create'
  resources :showrooms, only: [:index, :new, :create]
  resources :products, only: [:show]
  root to: 'pages#home'

  namespace :dashboard do
    root to: 'pages#home'
  end
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product, quantity)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += quantity.to_i
    else
      current_item = line_items.build(product_id: product.id, quantity: quantity.to_i)
    end
    current_item
  end

  def total_amount
    line_items.to_a.sum(&:total_price)
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :subcategories, dependent: :destroy
  has_many :products, through: :subcategories
  has_one_attached :image

  validates :category_name, presence: true, length: { maximum: 250 }
end

app/models/line_item.rb
# frozen_string_literal: true

class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

  def total_price
    product.price.to_i * quantity.to_i
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :subcategory
  has_many :line_items, dependent: :destroy

  validates :product_name, presence: true, length: { maximum: 250 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :dimensions, presence: true

  has_one_attached :image

  scope :outlet, -> { where(outlet: true) }
end

app/models/showroom.rb
# frozen_string_literal: true

class Showroom < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :adress, presence: true
  validates :phone, presence: true
  validates :mobile, presence: true
  validates :image_url, presence: true
end

app/models/subcategory.rb
# frozen_string_literal: true

class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :products, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true, length: { maximum: 250 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include CurrentCart
  before_action :set_cart
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # rubocop:disable Rails/I18nLocaleTexts

  # GET /carts/1
  # GET /carts/1.json
  def show; end

  # GET /carts/new
  def new; end

  # POST /carts
  # POST /carts.json
  def create; end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # rubocop:enable Rails/I18nLocaleTexts

  private

  # rubocop:disable Rails/I18nLocaleTexts
  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_path, notice: "That cart doesn't exist"
  end
  # rubocop:enable Rails/I18nLocaleTexts
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show]

  # GET /categories/1
  def show
    @subcategories = @category.subcategories
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/line_items_controller.rb
# frozen_string_literal: true

class LineItemsController < ApplicationController
  # rubocop:disable Rails/I18nLocaleTexts

  before_action :set_line_item, only: %i[update destroy]

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  def update
    @line_item.quantity = line_item_params[:quantity]

    if @line_item.save
      redirect_to @line_item.cart, notice: 'Item quantity updated successfully'
    else
      redirect_to @line_item.cart, notice: 'Error updating quantity'
    end
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(line_item_params[:product_id])
    @line_item = @cart.add_product(product, line_item_params[:quantity])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart, notice: 'Item added to cart.' }
      else
        format.html { render :new }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    cart_id = @line_item.cart_id
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to carts_path(id: cart_id), notice: 'Item successfully removed.' }
      format.json { head :no_content }
    end
  end

  # rubocop:enable Rails/I18nLocaleTexts

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.

  def line_item_params
    params.require(:line_item).permit(:product_id, :cart_id, :quantity)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
    @category = @product.subcategory.category
  end
end

app/controllers/showrooms_controller.rb
# frozen_string_literal: true

class ShowroomsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @showrooms = Showroom.all
  end

  def new
    @showroom = Showroom.new
  end

  def create
    @showroom = Showroom.new(showroom_params)

    if @showroom.save
      # redirect_to showroom_path(@showroom) #i think
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def showroom_params
    params.require(:showroom).permit(:name, :adress, :phone, :mobile, :email, :image_url, :geolocation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # rubocop:disable Rails/HelperInstanceVariable
  def cart_count_over_one
    @cart.line_items.sum(&:quantity)
  end

  def cart_has_items
    @cart.line_items.count.positive? if @cart
  end
  # rubocop:enable Rails/HelperInstanceVariable
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/line_items_helper.rb
# frozen_string_literal: true

module LineItemsHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/subcategories_helper.rb
# frozen_string_literal: true

module SubcategoriesHelper
end

app/helpers/types_helper.rb
# frozen_string_literal: true

module TypesHelper
end

app/views/carts/show.html.erb
<% if @cart.line_items.count > 0 %>
  <div class="container px-6 py-10 mx-auto view-height">
    <div class="text-right flex justify-end">
      <%= link_to 'Keep Shopping', root_path , class: 'ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium' %>
      <%= link_to 'Make order',"#" , class: 'ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium' %>
    </div>
    <section class="section p-2">
      <%= render(@cart.line_items) %>

      <div class="flex justify-between items-center p-2">
        <div class="column">
          <%= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "ml-2 rounded-lg py-3 px-5 bg-red-300 inline-block font-medium" %>
        </div>
        <div class="column total has-text-right">
          <h4 class="title is-4">
            <span class="f5 has-text-grey font-semibold">Total: <%= number_to_currency(@cart.total_amount) %></span>
          </h4>
        </div>
      </div>
    </section>
  </div>
<% else %>
  <div class="container px-6 py-10 mx-auto view-height text-center">
    <h1 class="text-4xl">No items added to cart</h1>
  </div>
<% end %>

app/views/categories/show.html.erb
<%if @category&.image.attached? %>
  <div class="bg-cover bg-center bg-repeat flex justify-center items-center mb-6 relative", style="background-image: url('<%= url_for(@category.image) %>'); height: 150px; width: 100%;">
    <div class="absolute top-0 left-0 right-0 bottom-0 bg-black opacity-40 z-40 h-full" style="background-color: black; opacity: 0.4; height: 100%;"> </div>
    <div class="w-full relative z-50">
      <div class="container text-left mx-auto">
        <div class="text-white text-4xl"><%= @category.category_name.upcase %></div>
      </div>
    </div>

  </div>
<% end %>

<% @subcategories&.each do |subcategory| %>

  <div class="bg-cover bg-center container  flex justify-center items-center mb-6 mx-auto relative", style="background-image: url('<%= url_for(subcategory.image) if  subcategory.image.attached?%>'); height: 250px; width: 90%;">
    <div class="absolute top-0 left-0 right-0 bottom-0 bg-black opacity-40 z-30 h-full" style="background-color: black; opacity: 0.4; height: 100%;"> </div>
      <div class="w-full relative z-50">
        <div class="text-center">
          <div class="text-white text-3xl mb-6"><%= subcategory.name.upcase %></div>
          <button>
            <%= link_to "See all products", subcategory, class: "block text-xl rounded py-2 px-6 bg-blue-600 hover:bg-blue-400 text-white" %>
          </button>
        </div>
      </div>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<hr>
<div class="flex flex-col justify-center items-center p-2 md:flex-row md:justify-between" >
  <div>
    <h3 class="w-full md:w-10"><%= line_item.product.product_name %></h3>
  </div>
  <div>
    <h3 class="w-full md:w-10"><%= truncate(line_item.product.dimensions, length: 140) %></h3>
  </div>
  <div>
    <% if line_item.product.image.attached? %>
      <%= image_tag(line_item.product.image, class: "w-24") %>
    <% end %>
  </div>
  <div>
  </div>
  <div>
    <h3><%#= line_item.quantity %></h3>
    <%= form_with model: line_item, local: true do |form| %>
        <%= form.hidden_field :product_id, value: line_item.product_id %>
        <%= form.number_field :quantity, {onchange: 'this.form.submit();', class: "w-16 rounded", min: 1} %>
    <% end %>
  </div>
  <div>
    <h3><%= number_to_currency(line_item.product.price, unit: "€", precision: 0, format: "%n %u") %></h3>
  </div>
    <div>
    <%= link_to 'Remove Item', line_item, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "ml-2 rounded-lg p-1 bg-red-300 inline-block font-medium" %>
  </div>
  <div>
    <h3><%= number_to_currency(line_item.total_price, unit: "€", precision: 0, format: "%n %u") %></h3>
  </div>
</div>
<hr>

app/views/products/show.html.erb
<section class="bg-white dark:bg-gray-900">
    <div class="container px-6 py-10 mx-auto">
        <div>
            <div class="text-gray-500 text-m">
                <%= link_to "home", root_path %> >
                <%= link_to @category.category_name , category_path(id: @category.id)  %> >
                <%= link_to @product.subcategory.name , subcategory_path(id: @product.subcategory.id)  %> >
                <%= @product.product_name %>
            </div>
        </div>
        <div class="lg:flex lg:items-start">
            <div class="w-full h-full space-y-12 lg:w-1/2 p-3">
                <div>
                    <h1 class="text-3xl font-semibold text-gray-800 capitalize lg:text-4xl dark:text-white"><%= @product.product_name %></h1>
                </div>

                <div class="md:flex md:items-start md:-mx-4">
                    <div class="mt-4 md:mx-4 md:mt-0">
                        <h1 class="text-2xl font-semibold text-gray-700 capitalize dark:text-white">Price: <%= number_to_currency(@product.price, unit: "€", precision: 0, format: "%n %u") %></h1>
                    </div>
                </div>

                <div class="md:flex md:items-start md:-mx-4">
                    <div class="mt-4 md:mx-4 md:mt-0">
                        <h1 class="text-2xl font-semibold text-gray-700 capitalize dark:text-white">Dimensions: <%= @product.dimensions %></h1>
                    </div>
                </div>
                <div class="md:flex md:items-start md:-mx-4">
                    <%= form_with model: @product.line_items.new, url: line_items_path do |form| %>
                        <%= form.hidden_field :product_id, value: @product.id %>
                        <%= form.number_field :quantity, min: 1, class: "w-24 rounded-lg py-3 text-gray-800 inline-block font-medium" %>

                        <%= form.submit 'Add to cart', class: " rounded-lg py-3 px-5 text-white bg-gray-800 inline-block font-medium" %>
                    <% end %>
                </div>
            </div>

            <div class="lg:flex lg:items-center lg:w-1/2 lg:justify-center">
              <% if @product.image.attached? %>
                <%= image_tag(@product.image, class: "object-cover w-full rounded drop-shadow-xl") %>
              <% else %>
                <%= image_tag("no_image.jpg", class: "object-cover w-full rounded drop-shadow-xl") %>
              <% end %>
            </div>
        </div>


    </div>
</section>