config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'products/show'
  resources :subcategories
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories, only: [:show]
  devise_for :users, controllers: { registrations: 'users/registrations'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get '/showrooms', to: 'showrooms#index'
  # get '/showrooms/new', to: 'showrooms#new'
  # post '/showrooms/create', to: 'showrooms#create'
  resources :showrooms, only: [:index, :new, :create]
  resources :products, only: [:show]
  root to: 'pages#home'

  namespace :dashboard do
    root to: 'pages#home'
  end
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product, quantity)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += quantity.to_i
    else
      current_item = line_items.build(product_id: product.id, quantity: quantity.to_i)
    end
    current_item
  end

  def total_amount
    line_items.to_a.sum(&:total_price)
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :subcategories, dependent: :destroy
  has_many :products, through: :subcategories
  has_one_attached :image

  validates :category_name, presence: true, length: { maximum: 250 }
end

app/models/line_item.rb
# frozen_string_literal: true

class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

  def total_price
    product.price.to_i * quantity.to_i
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :subcategory
  has_many :line_items, dependent: :destroy

  validates :product_name, presence: true, length: { maximum: 250 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :dimensions, presence: true

  has_one_attached :image

  scope :outlet, -> { where(outlet: true) }
end

app/models/showroom.rb
# frozen_string_literal: true

class Showroom < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :adress, presence: true
  validates :phone, presence: true
  validates :mobile, presence: true
  validates :image_url, presence: true
end

app/models/subcategory.rb
# frozen_string_literal: true

class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :products, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true, length: { maximum: 250 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # rubocop:disable Rails/I18nLocaleTexts

  # GET /carts/1
  # GET /carts/1.json
  def show; end

  # GET /carts/new
  def new; end

  # POST /carts
  # POST /carts.json
  def create; end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # rubocop:enable Rails/I18nLocaleTexts

  private

  # rubocop:disable Rails/I18nLocaleTexts
  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_path, notice: "That cart doesn't exist"
  end
  # rubocop:enable Rails/I18nLocaleTexts
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
    @category = @product.subcategory.category
  end
end

app/controllers/showrooms_controller.rb
# frozen_string_literal: true

class ShowroomsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @showrooms = Showroom.all
  end

  def new
    @showroom = Showroom.new
  end

  def create
    @showroom = Showroom.new(showroom_params)

    if @showroom.save
      # redirect_to showroom_path(@showroom) #i think
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def showroom_params
    params.require(:showroom).permit(:name, :adress, :phone, :mobile, :email, :image_url, :geolocation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # rubocop:disable Rails/HelperInstanceVariable
  def cart_count_over_one
    @cart.line_items.sum(&:quantity)
  end

  def cart_has_items
    @cart.line_items.count.positive? if @cart
  end
  # rubocop:enable Rails/HelperInstanceVariable
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/line_items_helper.rb
# frozen_string_literal: true

module LineItemsHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/subcategories_helper.rb
# frozen_string_literal: true

module SubcategoriesHelper
end

app/helpers/types_helper.rb
# frozen_string_literal: true

module TypesHelper
end

app/views/layouts/_flash.html.erb
<% if notice.present? %>
    <p class="py-2 px-4 bg-gray-200 w-full bg-gray-200 font-medium inline-block" id="notice"><%= notice %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-gray-900">
    <div class="container px-6 py-4 mx-auto ">
        <div class="lg:flex">
            <div class="w-full -mx-6 lg:w-2/5">
                <div class="px-6">
                    <div>
                      <%= link_to 'Brand', "#", class: "text-xl font-bold text-white hover:text-gray-300" %>
                    </div>

                    <p class="max-w-md mt-2 text-gray-400">Join 31,000+ other and never miss out on new tips, tutorials, and more.</p>

                    <div class="flex mt-4 -mx-2">
                        <%= link_to "#", class: "mx-2 text-gray-200 hover:text-gray-400" do%>
                          <svg class="w-4 h-4 fill-current" viewBox="0 0 512 512">
                              <path d="M444.17,32H70.28C49.85,32,32,46.7,32,66.89V441.61C32,461.91,49.85,480,70.28,480H444.06C464.6,480,480,461.79,480,441.61V66.89C480.12,46.7,464.6,32,444.17,32ZM170.87,405.43H106.69V205.88h64.18ZM141,175.54h-.46c-20.54,0-33.84-15.29-33.84-34.43,0-19.49,13.65-34.42,34.65-34.42s33.85,14.82,34.31,34.42C175.65,160.25,162.35,175.54,141,175.54ZM405.43,405.43H341.25V296.32c0-26.14-9.34-44-32.56-44-17.74,0-28.24,12-32.91,23.69-1.75,4.2-2.22,9.92-2.22,15.76V405.43H209.38V205.88h64.18v27.77c9.34-13.3,23.93-32.44,57.88-32.44,42.13,0,74,27.77,74,87.64Z"/>
                          </svg>
                        <% end %>
                        <%= link_to "#", class: "mx-2 text-gray-200 hover:text-gray-400" do%>
                          <svg class="w-4 h-4 fill-current" viewBox="0 0 512 512">
                              <path d="M455.27,32H56.73A24.74,24.74,0,0,0,32,56.73V455.27A24.74,24.74,0,0,0,56.73,480H256V304H202.45V240H256V189c0-57.86,40.13-89.36,91.82-89.36,24.73,0,51.33,1.86,57.51,2.68v60.43H364.15c-28.12,0-33.48,13.3-33.48,32.9V240h67l-8.75,64H330.67V480h124.6A24.74,24.74,0,0,0,480,455.27V56.73A24.74,24.74,0,0,0,455.27,32Z"/>
                          </svg>
                        <% end %>
                        <%= link_to "#", class: "mx-2 text-gray-200 hover:text-gray-400" do%>
                          <svg class="w-4 h-4 fill-current" viewBox="0 0 512 512">
                                <path d="M496,109.5a201.8,201.8,0,0,1-56.55,15.3,97.51,97.51,0,0,0,43.33-53.6,197.74,197.74,0,0,1-62.56,23.5A99.14,99.14,0,0,0,348.31,64c-54.42,0-98.46,43.4-98.46,96.9a93.21,93.21,0,0,0,2.54,22.1,280.7,280.7,0,0,1-203-101.3A95.69,95.69,0,0,0,36,130.4C36,164,53.53,193.7,80,211.1A97.5,97.5,0,0,1,35.22,199v1.2c0,47,34,86.1,79,95a100.76,100.76,0,0,1-25.94,3.4,94.38,94.38,0,0,1-18.51-1.8c12.51,38.5,48.92,66.5,92.05,67.3A199.59,199.59,0,0,1,39.5,405.6,203,203,0,0,1,16,404.2,278.68,278.68,0,0,0,166.74,448c181.36,0,280.44-147.7,280.44-275.8,0-4.2-.11-8.4-.31-12.5A198.48,198.48,0,0,0,496,109.5Z"/>
                            </svg>
                        <% end %>
                    </div>
                </div>
            </div>

            <div class="mt-6 lg:mt-0 lg:flex-1">
                <div class="grid grid-cols-2 gap-6 sm:grid-cols-3 md:grid-cols-4">
                    <div>
                        <h3 class=" uppercase text-white">Information</h3>
                        <%= link_to "Transport and assambling", "#", class: "block mt-2 text-sm text-gray-400 hover:underline" %>
                        <%= link_to 'After sales service', "#", class: "block mt-2 text-sm text-gray-400 hover:underline" %>
                        <%= link_to 'Payments', "#", class: "block mt-2 text-sm text-gray-400 hover:underline" %>
                    </div>

                    <div>
                        <h3 class="uppercase text-white">Partners</h3>
                        <%= link_to "Cilek", "#", class: "block mt-2 text-sm text-gray-400 hover:underline" %>
                        <%= link_to 'Almero', "#", class: "block mt-2 text-sm text-gray-400 hover:underline" %>
                        <%= link_to 'Company', "#", class: "block mt-2 text-sm text-gray-400 hover:underline" %>
                    </div>

                    <div>
                        <h3 class="uppercase text-white">Promotions</h3>
                        <%= link_to "Discounts", "#", class: "block mt-2 text-sm text-gray-400 hover:underline" %>
                        <%= link_to 'Outlet', "#", class: "block mt-2 text-sm text-gray-400 hover:underline" %>
                        <%= link_to 'Other', "#", class: "block mt-2 text-sm text-gray-400 hover:underline" %>
                    </div>

                    <div>
                        <h3 class="uppercase text-white">Contact</h3>
                        <span class="block mt-2 text-sm text-gray-400 hover:underline">+1 526 654 8965</span>
                        <span class="block mt-2 text-sm text-gray-400 hover:underline">example@email.com</span>
                    </div>
                </div>
            </div>
        </div>

        <hr class="h-px my-6 border-none bg-gray-700">

        <div>
            <p class="text-center text-white">© Brand 2020 - All rights reserved</p>
        </div>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<div class="fixed w-full left-0 top-0 bg-transparent z-10 h-screen hidden transition-all" id="backdrop"></div>
<nav class="shadow bg-gray-800 z-20 md:z-0 left-0 top-0 md:h-auto" id="navbar">
    <div class="container px-6 py-3 mx-auto">
        <div class="flex flex-col md:flex-row md:justify-between md:items-center">
            <div class="flex items-center justify-between">
                <div class="flex items-center">
                    <%= link_to 'Brand',  root_path, class: "text-2xl font-bold transition-colors duration-200 transform text-white lg:text-3xl hover:text-gray-300 cursor-pointer" %>

                    <!-- Search input on desktop screen -->
                    <div class="hidden mx-10 md:block">
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3">
                                <svg class="w-5 h-5 text-gray-400" viewBox="0 0 24 24" fill="none">
                                    <path d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                                </svg>
                            </span>

                            <input type="text" class="  w-full py-2 pl-10 pr-4 border rounded-md bg-gray-700 text-gray-300 border-gray-600 focus:border-blue-300 focus:outline-none focus:ring focus:ring-opacity-40 focus:ring-blue-300" placeholder="Search">
                        </div>
                    </div>
                </div>

                <!-- Mobile menu button -->
                <div class="flex md:hidden" id="hamburger-btn">
                    <button type="button" class="text-gray-200 hover:text-gray-400 focus:outline-none focus:text-gray-400" aria-label="toggle menu">
                        <svg viewBox="0 0 24 24" class="w-6 h-6 fill-current">
                            <path fill-rule="evenodd" d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"></path>
                        </svg>
                    </button>
                </div>
            </div>

            <!-- Mobile Menu open: "block", Menu closed: "hidden" -->
            <div class="items-center md:flex hidden md:block" id="mobile-menu">
                <div class="flex flex-col mt-2 md:flex-row md:mt-0 md:mx-1">
                    <%= link_to 'Home', root_path, class: "my-1 text-sm leading-5 transition-colors duration-200 transform text-gray-200 hover:text-blue-400 hover:underline md:mx-4 md:my-0 cursor-pointer" %>
                    <%= link_to 'About', "#", class: "my-1 text-sm leading-5 transition-colors duration-200 transform text-gray-200 hover:text-blue-400 hover:underline md:mx-4 md:my-0 cursor-pointer" %>
                    <%= link_to 'Catalogues', "#", class: "my-1 text-sm leading-5 transition-colors duration-200 transform text-gray-200 hover:text-blue-400 hover:underline md:mx-4 md:my-0 cursor-pointer" %>
                    <%= link_to 'Showrooms', showrooms_path, class: "my-1 text-sm leading-5 transition-colors duration-200 transform text-gray-200 hover:text-blue-400 hover:underline md:mx-4 md:my-0 cursor-pointer" %>
                </div>

                <div class="flex items-center py-2 -mx-1 md:mx-0">
                    <%= link_to cart_path(@cart), class: "relative transition-colors duration-200 transform text-gray-200 hover:text-gray-300 cursor-pointer"  do %>
                         <svg class="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M3 3H5L5.4 5M7 13H17L21 5H5.4M7 13L5.4 5M7 13L4.70711 15.2929C4.07714 15.9229 4.52331 17 5.41421 17H17M17 17C15.8954 17 15 17.8954 15 19C15 20.1046 15.8954 21 17 21C18.1046 21 19 20.1046 19 19C19 17.8954 18.1046 17 17 17ZM9 19C9 20.1046 8.10457 21 7 21C5.89543 21 5 20.1046 5 19C5 17.8954 5.89543 17 7 17C8.10457 17 9 17.8954 9 19Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>

                        <span class="absolute top-0 left-0 p-1 text-xs text-white bg-blue-500 rounded-full"></span>
                    <% end %>
                    <% if cart_has_items %>
                        <span class="inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-white bg-gray-500 rounded-full"><%= cart_count_over_one %></span>
                    <% end %>
                </div>
                <div class="md:flex">
                <% if user_signed_in? %>
                    <%= link_to "Dashboard", dashboard_root_path, class: "my-1 text-sm leading-5 transition-colors duration-200 transform text-gray-200 hover:text-blue-400 hover:underline md:mx-4 md:my-0 cursor-pointer" %>
                    <%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "my-1 text-sm leading-5 transition-colors duration-200 transform text-gray-200 hover:text-blue-400 hover:underline md:mx-4 md:my-0 cursor-pointer" %>
                <% else %>
                    <%= link_to "Sign in", user_session_path, class: "my-1 text-sm leading-5 transition-colors duration-200 transform text-gray-200 hover:text-blue-400 hover:underline md:mx-4 md:my-0" %>
                <% end %>
                </div>

                <!-- Search input on mobile screen -->
                <div class="mt-3 md:hidden">
                    <div class="relative">
                        <span class="absolute inset-y-0 left-0 flex items-center pl-3">
                            <svg class="w-5 h-5 text-gray-400" viewBox="0 0 24 24" fill="none">
                                <path d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                            </svg>
                        </span>

                        <input type="text" class="w-full py-2 pl-10 pr-4 bg-white border rounded-md bg-gray-800 text-gray-300 border-gray-600 focus:border-blue-400 focus:border-blue-300 focus:outline-none focus:ring focus:ring-opacity-40 focus:ring-blue-300" placeholder="Search">
                    </div>
                </div>
            </div>
        </div>

            <div class="py-1 mt-3 -mx-3 md:overflow-y-auto md:whitespace-nowrap md:scroll-hidden hidden md:block flex flex-col md:block" id="mobile-menu1">
            <% Category.all.each do |cat| %>
                <%= link_to cat.category_name.capitalize, category_path(cat), class: "mx-4 my-1 text-sm leading-5 transition-colors duration-200 transform text-gray-200 hover:text-blue-600 hover:text-blue-400 hover:underline md:my-0 cursor-pointer"  %>
            <% end %>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FurnitureStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "layouts/navbar"%>
    <%= render partial: "layouts/flash"%>
    <div class="view-height">
      <%= yield %>
    </div>

     <%= render partial: "layouts/footer"%>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FurnitureStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
  </head>

  <body >
    <div class="flex relative">
      <div class="hidden fixed space-y-0 right-0 w-60 lg:flex lg:relative" id="sideBar">
        <div class="fixed z-20 inset-0 bg-black opacity-50 transition-opacity lg:hidden"
          onclick="document.getElementById('sideBar').classList.toggle('hidden');"></div>

        <div :class="sidebarOpen ? 'translate-x-0 ease-out' : '-translate-x-full ease-in'"
          class="fixed z-30 inset-y-0 left-0 w-60 transition duration-300 transform bg-white dark:bg-gray-900 overflow-y-auto lg:translate-x-0 lg:static lg:inset-0">
          <div class="flex items-center justify-center mt-8">
            <div class="flex items-center">
              <span class="text-gray-800 dark:text-white text-2xl font-semibold">Dashboard</span>
            </div>
          </div>

          <nav class="flex flex-col mt-10 px-4 text-center">
            <%= link_to "Home", dashboard_root_path,
          class: "py-2 text-sm text-gray-700 dark:text-gray-100 bg-gray-200 dark:bg-gray-800 rounded" %>
            <%= link_to "My orders", "#",
            class: "mt-3 py-2 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-100  hover:bg-gray-200 dark:hover:bg-gray-800 rounded" %>
            <%= link_to "Account", edit_user_registration_path,
            class: "mt-3 py-2 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-800 rounded" %>
          </nav>
        </div>
      </div>

      <div class="w-full">
        <header class="flex justify-between items-center p-6">
          <div class="flex items-center space-x-4 lg:space-x-0">
            <div>
              <h1 class="text-2xl font-medium text-gray-800 dark:text-white">Welcome back, <%= current_user.email %></h1>
            </div>
          </div>

          <div class="flex items-center space-x-4">
            <button class="flex text-gray-600 dark:text-gray-300 focus:outline-none">
              <svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M15 17H20L18.5951 15.5951C18.2141 15.2141 18 14.6973 18 14.1585V11C18 8.38757 16.3304 6.16509 14 5.34142V5C14 3.89543 13.1046 3 12 3C10.8954 3 10 3.89543 10 5V5.34142C7.66962 6.16509 6 8.38757 6 11V14.1585C6 14.6973 5.78595 15.2141 5.40493 15.5951L4 17H9M15 17V18C15 19.6569 13.6569 21 12 21C10.3431 21 9 19.6569 9 18V17M15 17H9"
                  stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
              </svg>
            </button>

            <div x-data="{ dropdownOpen: false }" class="relative">
              <button @click="dropdownOpen = ! dropdownOpen"
                class="flex items-center space-x-2 relative focus:outline-none">
                <h2 class="text-gray-700 dark:text-gray-300 text-md font-semibold hidden sm:block mr-3"><%= current_user.email %></h1>
                </h2>
                <img class="h-9 w-9 rounded-full border-2 border-purple-500 object-cover"
                  src="https://images.unsplash.com/photo-1628260412297-a3377e45006f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1548&q=80"
                  alt="Your avatar">
              </button>

              <div class="absolute right-0 mt-2 w-48 bg-white rounded-md overflow-hidden shadow-xl z-10"
                x-show="dropdownOpen" x-transition:enter="transition ease-out duration-100 transform"
                x-transition:enter-start="opacity-0 scale-95" x-transition:enter-end="opacity-100 scale-100"
                x-transition:leave="transition ease-in duration-75 transform"
                x-transition:leave-start="opacity-100 scale-100" x-transition:leave-end="opacity-0 scale-95"
                @click.away="dropdownOpen = false">
                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-purple-600 hover:text-white">Profile</a>
                <%= link_to "Edit Profile", edit_user_registration_path, class:"block px-4 py-2 text-sm text-gray-700 hover:bg-purple-600 hover:text-white", role: "button" %>
                <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class:"block px-4 py-2 text-sm text-gray-700 hover:bg-purple-600 hover:text-white", role: "button" %>
              </div>
            </div>
            <button onclick="document.getElementById('sideBar').classList.toggle('hidden');"
              class="text-gray-500 dark:text-gray-300 focus:outline-none lg:hidden">
              <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M4 6H20M4 12H20M4 18H11" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                  stroke-linejoin="round" />
              </svg>
            </button>
          </div>
        </header>

        <div class="flex h-screen font-roboto">
          <main class="flex-1 overflow-x-none overflow-y-none">
            <div class="container mx-auto px-6 py-8">
              <%= render partial: "layouts/flash" %>
              <%= yield %>
            </div>
          </main>
        </div>
      </div>

    </div>
    <%= render partial: "layouts/footer" %>
  </body>
</html>